:8084 {
    reverse_proxy https://localhost:8443 {
        transport http {
            tls_insecure_skip_verify
        }
    }

    handle_errors 502 503 {
        rewrite * /maintenance.html
        file_server {
            root /etc/caddy
        }
    }
}
