#!/bin/bash
# collect-reference-system.sh — Capture the maintainer's reference rig
# into docs/reference-system.yml for the in-app About page.
#
# This is NOT a minimum/recommended spec. It is a snapshot of the single
# machine the maintainer uses — presented in the app and docs as one
# possible configuration, so users can see exactly what the project has
# been exercised against. See docs/ARCHITECTURE.md and README for the
# minimum and recommended specs.
#
# Usage: ./scripts/collect-reference-system.sh [output_path]
#   default output: docs/reference-system.yml
#
# Run this once per release (or whenever the maintainer's rig changes),
# commit the generated YAML, and ship it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT="${1:-${PROJECT_ROOT}/docs/reference-system.yml}"

safe() {
    # Run a command, echo a fallback if it fails or returns empty
    local fallback="$1"
    shift
    local out
    out="$("$@" 2>/dev/null || true)"
    if [[ -z "${out}" ]]; then
        echo "${fallback}"
    else
        echo "${out}"
    fi
}

cpu_model="$(safe unknown sh -c "lscpu | awk -F': +' '/^Model name/ {print \$2; exit}'")"
cpu_cores="$(safe unknown sh -c "lscpu | awk -F': +' '/^Core\\(s\\) per socket/ {print \$2; exit}'")"
cpu_threads="$(safe unknown sh -c "lscpu | awk -F': +' '/^CPU\\(s\\):/ {print \$2; exit}'")"
cpu_arch="$(safe unknown uname -m)"
mem_total="$(safe unknown sh -c "free -h | awk '/^Mem:/ {print \$2}'")"
gpu_model="$(safe "none detected" sh -c "lspci | grep -iE '(vga|3d|display)' | head -1 | sed 's/^[^:]*: //'")"
os_name="$(safe unknown sh -c ". /etc/os-release && echo \$PRETTY_NAME")"
os_id="$(safe unknown sh -c ". /etc/os-release && echo \$ID")"
kernel="$(safe unknown uname -r)"
mb_maker="$(safe unknown sh -c "sudo -n dmidecode -s baseboard-manufacturer 2>/dev/null || cat /sys/devices/virtual/dmi/id/board_vendor 2>/dev/null")"
mb_product="$(safe unknown sh -c "sudo -n dmidecode -s baseboard-product-name 2>/dev/null || cat /sys/devices/virtual/dmi/id/board_name 2>/dev/null")"
python_ver="$(safe unknown sh -c "python3 --version | awk '{print \$2}'")"
ffmpeg_ver="$(safe unknown sh -c "ffmpeg -version 2>&1 | head -1 | awk '{print \$3}'")"
sqlite_ver="$(safe unknown sh -c "sqlite3 --version | awk '{print \$1}'")"
openssl_ver="$(safe unknown sh -c "openssl version | awk '{print \$2}'")"
docker_ver="$(safe "not installed" sh -c "docker --version 2>/dev/null | awk '{print \$3}' | tr -d ','")"
caddy_ver="$(safe "not installed" sh -c "caddy version 2>/dev/null | head -1 | awk '{print \$1}'")"
app_version="$(safe unknown cat "${PROJECT_ROOT}/VERSION")"
generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$(dirname "${OUTPUT}")"

cat > "${OUTPUT}" <<YAML
# Maintainer's reference system — one possible configuration, not a
# minimum or recommendation. Generated by scripts/collect-reference-system.sh.
# See README.md (Hardware Requirements) and docs/ARCHITECTURE.md for the
# supported minimum and recommended specs.

generated_at: "${generated_at}"
app_version: "${app_version}"

hardware:
  cpu:
    model: "${cpu_model}"
    cores: ${cpu_cores}
    threads: ${cpu_threads}
    architecture: "${cpu_arch}"
  memory:
    total: "${mem_total}"
  gpu:
    model: "${gpu_model}"
    # NOTE: If this is a consumer AMD Radeon (RDNA 2 / RDNA 3), local GPU
    # transcription has been demonstrated to be unsafe on this class of
    # hardware. The maintainer uses remote GPU (Vast.ai / RunPod) for all
    # transcription work. See README.md for the cautionary tale.
  motherboard:
    manufacturer: "${mb_maker}"
    product: "${mb_product}"

operating_system:
  name: "${os_name}"
  id: "${os_id}"
  kernel: "${kernel}"

software:
  python: "${python_ver}"
  ffmpeg: "${ffmpeg_ver}"
  sqlite: "${sqlite_ver}"
  openssl: "${openssl_ver}"
  docker: "${docker_ver}"
  caddy: "${caddy_ver}"

notes:
  - "This is the single machine the project is developed and smoke-tested on."
  - "It is consumer hardware the maintainer happened to have — not chosen for AI workloads."
  - "Local GPU transcription is NOT exercised on this rig (see README cautionary tale)."
  - "All transcription and TTS work is routed to remote GPU providers (Vast.ai, RunPod)."
YAML

echo "Reference-system snapshot written: ${OUTPUT}"
